name: Build

on:
  push:
    branches:
      - 'master'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:

  name: Build

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:

 # Slackware build
  Slackware-build:
    name: 🐧 Slackware 15.0+
    runs-on: ubuntu-latest

    container:
      image: cluck25/imhex_build:latest

    steps:

       - name: 🧰 Checkout
         uses: actions/checkout@v3
         with:
            submodules: recursive

      # Slackware cmake build
       - name: 🛠 Build
         run: |
          mkdir -p build && cd build
          CC=gcc CXX=g++ cmake                          \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}        \
          -DCMAKE_C_FLAGS:STRING="-O2 -fPIC"            \
          -DCMAKE_CXX_FLAGS:STRING="-O2 -fPIC"          \
          -DCMAKE_INSTALL_PREFIX="/usr"                 \
          -DCMAKE_MAKE_PROGRAM="/usr/bin/gmake"         \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache            \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache          \
          -DUSE_SYSTEM_FMT=OFF                          \
          -DUSE_SYSTEM_YARA=OFF                         \
          -DUSE_SYSTEM_NLOHMANN_JSON=OFF                \
          -DUSE_SYSTEM_CAPSTONE=OFF                     \
          -DIMHEX_PATTERNS_PULL_MASTER=ON               \
          -DIMHEX_COMMIT_HASH_SHORT="${GITHUB_SHA::7}"  \
          -DIMHEX_COMMIT_HASH_LONG="${GITHUB_SHA}"      \
          -DLIB_SUFFIX=64                               \
          -DMAN_INSTALL_DIR=/usr/man                    \
          -DIMHEX_COMMIT_BRANCH="${GITHUB_REF##*/}"     \
          -DIMHEX_ENABLE_LTO=ON                         \
          -DIMHEX_USE_GTK_FILE_PICKER=ON                \
          ..
          make
          DESTDIR=InstallDir make install

       - name: 📜 Set version variable
         run: |
          IMHEX_VERSION=$(cat VERSION)

       - name: Make package
         run: |
          cd build/InstallDir
          mkdir -p install
          # These files are required during installpkg
          cp -a /tmp/doinst.sh ./install
          cp -a /tmp/slack-desc ./install

          makepkg -l y -c n /tmp/ImHex-1.32.2-x86_64-1.txz

       - name: ⬆ Upload ImHex-$IMHEX_VERSION-x86_64-1.txz
         uses: actions/upload-artifact@v3
         with:
          if-no-files-found: error
          name: Slackware .txz x86_64
          path: |
            /tmp/ImHex-1.32.2-x86_64-1.txz
